### ISSUE TITLE
Do not process.exit on signals

### ISSUE THREAD

**Issue by dzuelke** [godaddy/terminus#1]
A process that reacts to a signal (and choose not ignore it, but exit because of it) should not simply `exit`, but instead send that signal to itself (after of course resetting the signal handler), so that calling programs (or other processes) can determine the cause of the exit correctly. See https://www.cons.org/cracauer/sigint.html, which talks about this in the context of `SIGTERM` specifically, but it applies to al signals, and also more generally `WIFSIGNALED` and `WTERMSIG`, https://www.gnu.org/software/libc/manual/html_node/Process-Completion-Status.html#Process-Completion-Status.

So, for example, instead of calling `process.exit(0);` in  `cleanup`, do `process.removeListener(…)` (that's how I assume it works in Node), and then `process.kill(process.pid, 'SIGTERM');` to kill the current process with the same signal that was received (so that the default process handling kicks in).

It's easy to test this on the shell: run a terminus example in the foreground, then `kill $terminuspid` from another shell. After it has quit, running `echo $?` in the first shell should display `128+$signalcode`, where "$signalcode" is the number of the signal, in this case 15 (SIGTERM, the `kill` default), for a total exit status of 143.

Similarly, when running a program and then Ctrl+C-ing out, the exit status should not be 0, but instead 130: 128 plus 2 (the SIGINT code).

Note that `process.exit(128+signal)` is not a solution. It's just bash that displays the exit condition as 128+signal. Programs must send the kill command to self.

An example of a Unix program doing it correctly, demonstrated with SIGINT for simplicity:

```ShellSession
$ sleep 2
^C
$ echo $?
130
```

**Comment by gergelyke** [comment]
Thanks @dzuelke! Can you send a PR addressing this?

**Comment by gergelyke** [comment]
@dzuelke I am going to work in this :)

**Comment by gergelyke** [comment]
@dzuelke can you take a look? https://github.com/godaddy/terminus/pull/3

**Comment by dzuelke** [comment]
Looks good!

I guess the general question is how to allow e.g. canceling handling (to ignore the signal instead of doing anything), or how to handle other signals gracefully (say SIGINT), but that's another issue entirely :)

**Comment by aeimer** [comment]
So actually because of this behaviour (quit with an uncaught SIGTERM) my containers exit with SIGTERM (which our APM considers as an error) or they get SIGKILL'ed as they don't quit at all. I Tried it with and without dumb-init and on alpine3.15 and bullseye. I honstly don't know if the SIGTERM exit is the best/correct method to quit. Some sources say, yes its correct, others say you should exit with an 0. The solution to run system.exit(0) in onShutdown seems kinda appropirate, but if that is a solution that is meant to go, we should make it configurable?!

@dzuelke @gergelyke 

related #209 #156

**Comment by dzuelke** [comment]
It is definitely correct behavior. The process terminating itself with the signal it received allows the process that is executing it to check the termination reason using `WIFSIGNALED`.

Containers are notoriously broken when it comes to signal forwarding. Ctrl+Cing out of a Docker run makes everything hang more often than not. Termination status often isn't bubbled up correctly.
