### ISSUE TITLE
Doesn't work with PM2

### ISSUE THREAD

**Issue by vernak2539** [godaddy/terminus#10]
Could this possibly get working with PM2? 

From [this post](https://nemethgergely.com/nodejs-healthcheck-graceful-shutdown/) it states that once the hypervisor sends a `SIGTERM` this module will facilitate graceful shutdown. PM2 seems to send a `SIGINT` instead ([docs](http://pm2.keymetrics.io/docs/usage/signals-clean-restart/#explanation-signals-flow)). Would this be able to be added or is this outside the scope of the project?

Would be happy to give it a go if the scope allows it

**Comment by gergelyke** [comment]
@vernak2539 one possible way to tackle this is to provide an option in terminus to modify the termination signal - would you be up to contribute it?

**Comment by gergelyke** [comment]
Ahh, I see the PR 🎉 

Do you think it would make sense to change it the way I proposed?

**Comment by vernak2539** [comment]
I've updated the PR to generalise the signal use. Would be helpful if you could give me some feedback on the param names used in the PR.

**Comment by solognt** [comment]
I was also looking for this but in my case I need both SIGTERM and SIGINT to do a graceful shutdown of the application. We run our application in 2 situations inside docker (SIGTERM) and also directly on the server using pm2 (SIGINT). So it would be nice to support an array of signals.

**Comment by vernak2539** [comment]
@solognt would you be able to open another issue? I think this is fundamentally different than the issue opened here and thus the work being done to add this feature is inherently different.

**Comment by gergelyke** [comment]
released as v2.2.0
