### ISSUE TITLE
healthcheck responses

### ISSUE THREAD

**Issue by tony-kerz** [godaddy/terminus#108]
is there any particular reason that healthcheck success responses repeat `info` in both `info` and `details` fields [here](https://github.com/godaddy/terminus/blob/master/lib/terminus.js#L26-L27), similar for failure responses [here](https://github.com/godaddy/terminus/blob/master/lib/terminus.js#L44-L45).

on a related note, is the format of `{info, details}` and `{error, details}` some kind of de-facto standard from somewhere?

generally wondering how you might feel about just using the object returned from the healthcheck verbatim instead of current formatting, or perhaps allow such behavior via some kind of opt-in?

perhaps something closer to the following?:
```
async function sendSuccess (res, options) {
  res.statusCode = 200
  res.setHeader('Content-Type', 'application/json')
  if (options) {
    return res.end(JSON.stringify({
      status: 'ok',
      ...options
    }))
  }
  res.end(SUCCESS_RESPONSE)
}
```

**Comment by gergelyke** [comment]
hi @tony-kerz 

> is there any particular reason that healthcheck success responses repeat info in both info and details fields here, similar for failure responses here.

it was to make sure it's a non-breaking change, when we started using the details field

> on a related note, is the format of {info, details} and {error, details} some kind of de-facto standard from somewhere?

If I remember correctly, that's what Kubernetes health check recommend? I am not sure.

Regarding the future, I think that makes sense - do you want to open a PR for it?
