### ISSUE TITLE
Do not send 503 on shutdown

### ISSUE THREAD

**Issue by florianmutter** [godaddy/terminus#112]
According to https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#when-should-you-use-liveness-or-readiness-probes it is not necessary to send 503 on shutdown.

> Note that if you just want to be able to drain requests when the Pod is deleted, you do not necessarily need a readiness probe; on deletion, the Pod automatically puts itself into an unready state regardless of whether the readiness probe exists. The Pod remains in the unready state while it waits for the Containers in the Pod to stop.

See also https://freecontent.manning.com/handling-client-requests-properly-with-kubernetes/

I think it should be avoided to have more meaning full event logs of the pods. Otherwise each shutdown generates logs of failed readiness requests

**Comment by rexxars** [comment]
@gergelyke Would you want this to be configurable, or the default behavior?

**Comment by gergelyke** [comment]
@rexxars imho this should be opt-in, so it's not a breaking change

**Comment by rexxars** [comment]
> is this something you could help with?

Sure! I took a stab at it in #172
