### ISSUE TITLE
Advertising package

### ISSUE THREAD

**Issue by traverseda** [godaddy/terminus#118]
It looks like this project depends on https://github.com/feross/funding, a project intended to show advertising in a projects build log.

I'm not familiar with your project, I'm just looking through a list of projects that depend on `feross/funding`. It's my understanding that right now there aren't any advertising messages actually showing, but if you're uncomfortable with the possibility of advertisements in build logs that's something you might want to look into.

**Comment by gergelyke** [comment]
Standard is only a dev dependency - it won't show up for folks using terminus.

Thanks for reaching out though!
