### ISSUE TITLE
stoppable incorrect usage

### ISSUE THREAD

**Issue by ashymanel92** [godaddy/terminus#119]
It's more a suggestion, haven't figured out how to make a PR (if this repo is even opend for PRs). Anyways:

1. `stoppable` is a constructor that returns server, it's not a function that will immediately stop server: <https://github.com/hunterloftis/stoppable/blob/master/lib/stoppable.js#L20>

2. it needs to be assigned to variable(name is just an example), and then used to stop server. 
3. no need for any binding in this case.

```
const stoppableServer = stoppable(server, timeout)
const asyncServerStop = promisify(stoppableServer.stop)
```

**Comment by gergelyke** [comment]
From the stoppable docs, on `stoppable()`:

`Decorates the server instance with a stop method. Returns the server instance, so can be chained, or can be run as a standalone statement`
