### ISSUE TITLE
Make the route of a healthcheck case insensitive

### ISSUE THREAD

**Issue by gdoron** [godaddy/terminus#123]
Would you accept a pull-request making the health-check case-insensitive (opt-in)?
By default, routes in Express are case-insensitive, in terminus, they are.

Caused by this line:
https://github.com/godaddy/terminus/blob/f36dbad24233f8c9065d032ec3d1436b8b5c7347/lib/terminus.js#L68

**Comment by gergelyke** [comment]
hi @gdoron - that makes perfect sense!

**Comment by gdoron** [comment]
@gergelyke done.
