### ISSUE TITLE
[Question] readiness checks 

### ISSUE THREAD

**Issue by EdenTurgeman** [godaddy/terminus#137]
After configuring terminus to work for our needs and verifying the basic health-check is working with postman, I realized i did not understand how/where am i supposed to implement a basic readiness probe. 
Is it supposed to be another route in the `healthchecks` object? or is that implemented for me?
I just wanted some clarification/examples on implementing a readiness route.

**Comment by gergelyke** [comment]
Hey - you just have to implement the `healthCheck` function, as seen in the example of the readme. The route is automatically added for you. You can find an example here https://github.com/godaddy/terminus/blob/master/example/mysql/index.js#L21-L30

**Comment by levibostian** [comment]
@EdenTurgeman, I was wondering the same exact thing after reading the docs. I assumed that I would need a readiness endpoint along with a liveness endpoint (I am a k8s noob). 

After [finding this blog post](https://nemethgergely.com/nodejs-healthcheck-graceful-shutdown/) and reading the source code, you *can* add more endpoints in the `healthchecks` object like you mentioned in your original question. terminus, to me, sounds like a project that does all of the piping but it still requires you to finish the job with kubernetes. Which, I have enjoyed about it. Tiny, simple, but yet powerful enough and very flexible. 

You tell k8s through probe config what endpoint to call for what probe. So, you can add as many endpoints as you wish for all different purposes with terminus. Including readiness and liveness.
