### ISSUE TITLE
Verbatim option in type def - please tag.

### ISSUE THREAD

**Issue by enition** [godaddy/terminus#139]
Is it possible to get this type definition change tagged and updated on npm?

https://github.com/godaddy/terminus/blob/681d430bfe40b5b6bf73dc0e3e77660eb01f8dd9/typings/index.d.ts#L11

**Comment by gergelyke** [comment]
@JacopoDaeli can you take a look at the semantic release process? it should have been released, but on npm the last publish was 3 months ago

**Comment by gergelyke** [comment]
closing this- going to cut a release manually today

**Comment by gergelyke** [comment]
@enition released under 4.4.0
