### ISSUE TITLE
Securing healthcheck endpoints

### ISSUE THREAD

**Issue by abhishek2244** [godaddy/terminus#149]
Hi,

Is there any way with which we could secure our health check endpoints like Basic Auth, OAuth 2 etc. ?
This could help the application to overcome DDOS attacks on open health check endpoints if they are directly checking DB states, external services etc.

If it is not present, is it there in the roadmap?

Thanks,

**Comment by gergelyke** [comment]
Hey - I believe this functionality should not be part of this library but should be handled on the load balancer level. Maybe something like this https://medium.com/monstar-lab-bangladesh-engineering/configure-basic-authentication-for-cloudfront-using-lambda-edge-c23ce46216d7 or https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/
