### ISSUE TITLE
Request to release 4.4.2

### ISSUE THREAD

**Issue by mmadson** [godaddy/terminus#161]
Hey folks, I see that you tagged a new release version to resolve a vulnerability flag. We are encountering the same vulnerability, any chance we can release 4.4.2 to registry? Much appreciated.

**Comment by rxmarbles** [comment]
> Hey folks, I see that you tagged a new release version to resolve a vulnerability flag. We are encountering the same vulnerability, any chance we can release 4.4.2 to registry? Much appreciated.

Hey @mmadson I'm working on it. Looks like something with the CICD failed. Looking to get that fixed and should get a new version published in the next day or so

**Comment by mmadson** [comment]
@rxmarbles Just a friendly reminder to push this to the top of your stack. Also willing to help if you accept contributions -- not sure what the process is for contributing to your CI system though...

**Comment by gergelyke-dd** [comment]
@rxmarbles any update on your end? I am happy to cut a release manually later tonight

**Comment by rxmarbles** [comment]
Sorry for the delay, been a bit busy non-opensource wise. @gergelyke-dd if you can get a manual release out that would be great. I'm working on converting the CI system to Github Actions and have a branch up for that though want to make sure we get similar functionality as we had w/ travis-ci 😄 . I should be able to make progress on this tonight

**Comment by rxmarbles** [comment]
@mmadson @gergelyke-dd Published the newest version `4.5.0`. Will continue working on CI to get this back into proper shape but should unblock for now
