### ISSUE TITLE
Add example code for PostgreSQL graceful shutdown

### ISSUE THREAD

**Issue by gergelyke** [godaddy/terminus#17]

**Comment by lukaszewczak** [comment]
Hi Gergely, as I wrote in twitter I would like to try to do this at first with PostgreSQL example :-) but could you please give me more details how this example should look like,  thanks

**Comment by gergelyke** [comment]
Hi @lukaszewczak ! thanks a lot! :)

Essentially, it would use one [node-postgres](https://node-postgres.com), create a connection to a server, then close it using terminus and [client.end](https://node-postgres.com/api/client#client-end-cb-err-error-gt-void-gt-void)

What do you think?

**Comment by lukaszewczak** [comment]
Looks good to me :-) Ok I will work on it during the weekend, maybe I try to do other examples (#19, #18, #16  ). Have a nice weekend!

**Comment by gergelyke** [comment]
🎉 
have a nice weekend too! :)

**Comment by gergelyke** [comment]
hi @lukaszewczak! how did it go? let me know if you need any help!

**Comment by lukaszewczak** [comment]
hi @gergelyke I'm sorry I've got some issues with project in my job and I spend all weekend on it, but I finished it today. I will try to send PR to the end of this week.

**Comment by gergelyke** [comment]
Added in https://github.com/godaddy/terminus/pull/21
