### ISSUE TITLE
Upgrade mongoose package version in example directory

### ISSUE THREAD

**Issue by maulik-fua** [godaddy/terminus#170]
https://github.com/godaddy/terminus/blob/master/example/mongoose/package.json
{
  "name": "mongoose",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "mongoose": "^5.4.2"
  }
}

The version of the mongoose is old and it is vulnerable. It would be must recommend to change/upgrade with the latest version( > 5.7.5).

**Comment by gergelyke** [comment]
@maulik-fua can you send a PR please?

**Comment by gergelyke** [comment]
Closed via https://github.com/godaddy/terminus/pull/171
