### ISSUE TITLE
How to attach tracer to shutdown in Express app?

### ISSUE THREAD

**Issue by franz-josef-kaiser** [godaddy/terminus#174]
In an express app, roughly written like the following snippet, I have added 
* Tracing via `'jaeger-client'`
* shutdown handling via `'terminus'`

#### Terminus/ Shutdown Handler
Terminus is wrapped in a callback, having the `server` as argument.
```js
export const shutdownHandler = server => {
   createTerminus(server, { … })
}
```
#### Server
The `tracer` gets just required in the main `server.js`. It does not export anything.
```js
require('./api/tracer')
middlewares(app)
routes(app)
const server = spdy.createServer(options, app)
shutdownHandler(server)
server.listen(port, error => {
    if (error) {
        console.error(error)
        return process.exit(1)
    }
    console.info(`Server listening on ${port}.`)
})
```
#### Tracer
The tracer will be set globally.
```js
// Init the tracer.
const tracer = initTracer(config, options)
// Make it globally available.
opentracing.initGlobalTracer(tracer)
```
#### Middlewares
Most stuff happens in middlewares, which is where the tracer injects itself to the `req`uest object.
```js
app.use((req, res, next) => {
    const tracer = opentracing.globalTracer()
    // (i) Extract parent context (header: Trace ID of original request from Ingress Controller/ Reverse Proxy/ Load Balancer/ Service Mesh).
    const wireCtx = tracer.extract(opentracing.FORMAT_HTTP_HEADERS, req.headers)
    // (i) Start span for current application/ component.
    req.span = tracer.startSpan(req.path, {
        childOf: wireCtx,
        tags: {
            [opentracing.Tags.SPAN_KIND]: opentracing.Tags.SPAN_KIND_RPC_SERVER,
            [opentracing.Tags.COMPONENT]: 'backend'
        }
    })
})
```
#### Routes
In the router, the span gets filled with additional information.
```js
app.route('/').get(function (req, res, next) {
    req.span.log({event: 'routing_cb', path: '/'})
    res.status(200)
        .type('text/plain')
        .send(`hi`)
})
```
### Question
Before utilizing `terminus`, I simply had a middleware that would attach callbacks. In there, I could add additional tags for or log to the tracer.
```js
app.use((req, res, next) => {
  process.on(<signal>, signal => {
    req.span.setTag(opentracing.Tags.HTTP_STATUS_CODE, req.statusCode)
    req.span.setTag(opentracing.Tags.HTTP_URL, req.path)
    req.span.setTag(opentracing.Tags.HTTP_METHOD, req.method)
    process.exit(0)
  })
  next()
})
```
**Question:** How can I use `terminus` in a way, so I have access to current `req`uest object and can call the tracers functions? Thanks in advance!

**Comment by gergelyke** [comment]
thank you for the super detailed issue @franz-josef-kaiser ❤️ 

I think that once you remove the `process.exit` call in the snippet below, things will work as expected

```js

app.use((req, res, next) => {
  process.on(<signal>, signal => {
    req.span.setTag(opentracing.Tags.HTTP_STATUS_CODE, req.statusCode)
    req.span.setTag(opentracing.Tags.HTTP_URL, req.path)
    req.span.setTag(opentracing.Tags.HTTP_METHOD, req.method)
  }) 
  next()
})
```

The reason being, the `process` modules is an event emitter as well, so whatever signal you'll listen for, both your app code and terminus will receive it.

Can you verify that it's the case?

**Comment by franz-josef-kaiser** [comment]
Thanks for your fast response and open sourcing this repo @gergelyke!

First, I wanted to respond, that I aimed at getting the `req`uest object to `terminus` and that you might have misunderstood me. Then I looked at it again and asked myself why I would violate the single responsibility of each pkg here? Probably just because `terminus` accepts the injection of a `logger` object… but who knows. In short, I added a middleware, unrelated to terminus, that handles shutdown logging. The following is tested and I am just leaving it here, so later readers might have something to build upon.

```js
app.use((req, res, next) => {
    const traceError = (err, req) => {
        req.span.setTag(opentracing.Tags.ERROR, true)
        req.span.log({
            event: 'request_error',
            'error.object': err,
            message: `${err.toString() || 'Internal Server Error'}`,
            stack: err.stack,
        })
        req.span.finish()
        console.log('traceError')
    }
    const traceShutdown = signal => {
        req.span.log({
            event: 'request_shutdown',
            message: `Reason: ${signal}`,
        })
        req.span.finish()
        console.log('traceShutdown',signal)
    }
    // Promise error
    process.on('unhandledRejection', err => traceError(err, req))

    // (i) Program crash.
    process.on('uncaughtException', err => traceError(err, req))

    // (i) Successful process termination (restart, etc.).
    process.on('SIGTERM', signal => traceShutdown(signal))

    // (i) control-C (^-C) keyboard event
    process.on('SIGINT', signal => traceShutdown(signal))

    // (i) control-C (^-C) keyboard event, but includes core dump.
    process.on('SIGQUIT', signal => traceShutdown(signal))

    next()
})
```

_Test: Add `process.kill(process.pid, 'SIGTERM')` as last middleware, reload your web app._
