### ISSUE TITLE
Custom status code on healthcheck

### ISSUE THREAD

**Issue by fabioimpe** [godaddy/terminus#176]
Hi,
I was trying to set a custom status code on my healthcheck without success.
For instance I need to both customize the contract and the status code, but for what I can see from the code the failure is triggered by raising an Error, but in that way I cannot customise the contract.

Is this achievable in some way?
Thanks

**Comment by gergelyke** [comment]
hey @fabioimpe - as of right now, it's not possible due to https://github.com/godaddy/terminus/blob/5a442dff3783a1e0ccb51caef3b948cb2acb7ab6/lib/terminus.js#L57

I'd be happy to accept a PR which checks if an error has a `statusCode` property, and if it has, it uses that instead of `503`

**Comment by sindilevich** [comment]
@gergelyke, @rxmarbles, thank you for advancing code changes that seem to resolve this issue now, since https://github.com/godaddy/terminus/pull/190 was merged in.
