### ISSUE TITLE
How can I control the termination?

### ISSUE THREAD

**Issue by 0Ams** [godaddy/terminus#181]
I have a different connection to the http server. When a problem occurs, process.emit ('sigterm') allows each handler to terminate.
However it is not able to process properly because it is killing process through process.kill in 'Godaddy/terminus'. 

How can i control stop the 'Godaddy/terminus' from process.kill?

**Comment by 0Ams** [comment]
https://github.com/godaddy/terminus/pull/182

I need an option that functions like above.

**Comment by gergelyke** [comment]
I am not sure if I understand your use-case - can you help me more here? Are you using the cluster module? Can you create a code snippet that repros your issue?

**Comment by gergelyke** [comment]
@0Ams can you please add a self-contained example I can easily run?
