### ISSUE TITLE
Expose a current state to a health check

### ISSUE THREAD

**Issue by okv** [godaddy/terminus#184]
Hey there!

Would be useful when implementing a health check to have a current state.
The state could be used to include it into a response, to fail only some of health checks during shutdown (e.g. when implementing liveness and readiness for k8s), etc.  

Possible implementation could be turning this:

https://github.com/godaddy/terminus/blob/5a442dff3783a1e0ccb51caef3b948cb2acb7ab6/lib/terminus.js#L88

into something like:

```js
info = await healthCheck({state})
```

What do you guys think?

Btw, terminus is great, thanks a lot for your efforts.

**Comment by gergelyke** [comment]
Hey!

I am not sure if I fully understand - where would the state come from?

**Comment by okv** [comment]
I just meant to share the `state` variable which is defined here:

https://github.com/godaddy/terminus/blob/5a442dff3783a1e0ccb51caef3b948cb2acb7ab6/lib/terminus.js#L168

and passed to most of the functions including:

https://github.com/godaddy/terminus/blob/5a442dff3783a1e0ccb51caef3b948cb2acb7ab6/lib/terminus.js#L75

to health check functions to make it possible to do something like this:

```js
createTerminus(server, {
  healthChecks: {
    '/live': ({ state }) => {
      // liveness checks here
      return Promise.resolve();
    },
    '/ready': ({ state }) => {
      if (state.isShuttingDown) {
        // always fail readiness when shutting down
        return Promise.reject(new Error('Shutting down'));
      } else {
        // readiness checks here
        return Promise.resolve();
      }
    }
  }
});

```

**Comment by gergelyke-dd** [comment]
huh, that makes sense - would you mind sending a PR?

**Comment by okv** [comment]
Alright, I'll try to take a look at it shortly

**Comment by okv** [comment]
There is the PR #185

**Comment by okv** [comment]
done in #185
