### ISSUE TITLE
Configurable health response options via middleware?

### ISSUE THREAD

**Issue by Noah-CompozeLabs** [godaddy/terminus#195]
Currently I'm using `terminus` in conjunction with `express`. I'm using the `cors` middleware.

I have a React frontend that occasionally hits the `/health` endpoint generated by `terminus` and tracks whether or not the API is healthy.

However, the health endpoints generated by `terminus` do not set any CORS headers or allow any middleware to be used: https://github.com/godaddy/terminus/blob/7eb6efaeef910d0b5bdae79c4e70474cbfde1b10/lib/terminus.js#L82-L94

So my frontend cannot make a request to the health endpoint.

For now my solution is to just not use `terminus`' healthchecks, but I wonder if there is a way to do this that I just haven't found yet?

**Comment by humphd** [comment]
This is something we would love to see get added as well.  I was just coming here to file it!

**Comment by LuigiZaccagnini** [comment]
I can take this issue!

**Comment by LuigiZaccagnini** [comment]
@rxmarbles I was wondering how I should approach adding CORS?

**Comment by LuigiZaccagnini** [comment]
Hey @rxmarbles , 

I was looking through the `terminus.js` and came up with a couple solutions: 

```
     return async (req, res) => {
      const url = caseInsensitive ? req.url.toLowerCase() : req.url
      const healthCheck = healthChecks[url]

      res.writeHead(200, 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'OPTIONS, POST, GET');

      if (healthCheck) {
        return check(healthCheck, res)
      } else {
        listener(req, res)
      }
``` 
This is a quick band aid solution that can have CORS working. The only problem I find with this solution is allowing all origins access so maybe we could add parameter to function for an array origins? 



Another solution I was thinking about was taking a parameter of all the middleware and looping to add them to the server:     
```
function decorateWithHealthCheck (server, state, options) {
  const { healthChecks, logger, onSendFailureDuringShutdown, sendFailuresDuringShutdown, caseInsensitive, statusOk, statusError, middleware } = options

 foreach.middleware((element) => { 
     server.use(element);
 }

  let hasSetHandler = false
  const createHandler = (listener) => {
    const check = hasSetHandler
      ? () => {}
      : async (healthCheck, res) => {
        if (state.isShuttingDown && sendFailuresDuringShutdown) {
          return sendFailure(res, { onSendFailureDuringShutdown, statusError })
        }
        let info
        try {
          info = await healthCheck({ state })
        } catch (error) {
          logger('healthcheck failed', error)
          return sendFailure(res, { error: error.causes, exposeStackTraces: healthChecks.__unsafeExposeStackTraces, statusCode: error.statusCode, statusError })
        }
        return sendSuccess(res, { info, verbatim: healthChecks.verbatim, statusOk })
      }


    hasSetHandler = true


    return async (req, res) => {
      const url = caseInsensitive ? req.url.toLowerCase() : req.url
      const healthCheck = healthChecks[url]
      if (healthCheck) {
        return check(healthCheck, res)
      } else {
        listener(req, res)
      }
    }
  }
```

We could also use [compose-middleware](https://github.com/blakeembrey/compose-middleware) to neatly add the multiple middleware into the server:

```
server.use(
  compose([
    function(req, res, next) {},
    function(err, req, res, next) {},
    function(req, res, next) {}
  ])
);
```

or with the parameter 

```
server.use(
  compose([
    middleware
  ])
);
```

I was wondering what you thought about each solution and which approach you'd like me to take.
