### ISSUE TITLE
Missing typing information for headers

### ISSUE THREAD

**Issue by ste2425** [godaddy/terminus#199]
The brilliant headers work added in #198 sadly forgot to update the typing's information for the `TerminusOptions` interface.

We can work around this locally by extending the interface (kudos for making it publicly available 👍).

```ts
interface TerminusOptionsWithHeaders extends TerminusOptions {
    headers?: { [key: string]: string };
}
```

Ideally the typing's should be updated however.

**Comment by gergelyke** [comment]
Thanks for opening the issue Stephen! Any chance you could submit a PR adding it?

**Comment by ste2425** [comment]
@gergelyke Beat you to it, already done :) #200
