### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by remojansen** [godaddy/terminus#2]
I'm working on a [TypeScript framework](https://github.com/ZafiroJS/zafiro) and this module would be a great addition but I need TypeScript support. 

The required changes are:

- Create a file `/typings/index.d.ts` (definitions)
- Create a file `/typings/index-test.ts` (definitions tests)
- Add a field to the package.json pointing to the `/typings/index.d.ts` file.
- The `/typings/index.d.ts` file will require an update If you change the public interface of the module.

I'm happy to send a PR to add TypeScript support. Would you accept such PR?

**Comment by gergelyke** [comment]
Hi @remojansen - sure thing! Thanks in advance 👌

**Comment by gergelyke** [comment]
merged 🎉
