### ISSUE TITLE
Example’s usage of healtcheck seems wrong

### ISSUE THREAD

**Issue by ryuheechul** [godaddy/terminus#25]
https://github.com/godaddy/terminus/blob/9c96f21b227b2e7770b942229f7a3c99b352c4ca/example/index.js#L18 this above should be like below 

```js
healthChecks: {
  '/healthz': () => Promise.resolve()
},
```
according to README.md and the code below https://github.com/godaddy/terminus/blob/8e822bacc9a4bf13b6834805ff2a20b19a67c0f5/lib/terminus.js#L67-L79

**Comment by gergelyke** [comment]
Great catch, thanks @ryuheechul! fixing now :)

**Comment by gergelyke** [comment]
fixed in https://github.com/godaddy/terminus/commit/a58062113ba19ba2279c22e99eba1ebdbd10b646
