### ISSUE TITLE
Add precommit githooks for consistent contributions

### ISSUE THREAD

**Issue by itaditya** [godaddy/terminus#36]
When a person makes some changes and commits them, he may not remember to format or lint his code, Due to this his PR may get rejected. To avoid this and allow faster, smoother contributions you should integrate precommit githooks in the project. This way certain commands will execute whenever someone makes a commit. I would love to make a PR regarding this.

**Comment by gergelyke** [comment]
Great, if you could send a PR, that'd be awesome!
