### ISSUE TITLE
4 Tests failing on Windows

### ISSUE THREAD

**Issue by itaditya** [godaddy/terminus#37]
![image](https://user-images.githubusercontent.com/15871340/36950480-6eeaed74-201c-11e8-8f0c-0098f758dedc.png)

I did read the *Limited Windows support* note but it mentioned that only `SIGTERM` doesn't work. Are all the failing tests dependent on `SIGTERM` ? If so, then I think I'll need to run `terminus` in a Docker environment.

**Comment by gergelyke** [comment]
Yes they are - Windows does not support signals at all.
