### ISSUE TITLE
Use async/await syntax along with try/catch

### ISSUE THREAD

**Issue by itaditya** [godaddy/terminus#38]
Current code is using `.then()` and `.catch()`. I think it's better if `async/await` is used instead. I would like to make a PR regarding this.

**Comment by gergelyke** [comment]
Hi @itaditya! 

thanks for the feedback - we wanted support Node.js 6 till it is supported by the foundation (April 2019). I hope that makes sense.

**Comment by itaditya** [comment]
Ok cool :+1:
