### ISSUE TITLE
Use parameter desctructuring with defaults for concise code

### ISSUE THREAD

**Issue by itaditya** [godaddy/terminus#39]
Consider a snippet of code taken from the module 
```js
function terminus(server, options = {}) {
  const { signal, timeout } = options;

  const signal = options.signal || 'SIGTERM';
  const timeout = options.timeout || 1000;
  //other stuff
}
```

Here the second argument of the `terminus` function is not destructured. Instead in the first line of the function body, desctructuring is being done. This can definitely be shortened. Another thing is, during destructuring we can use default values right there, However here it has not been used. If both of these facilities are used the code would look much more concise. Check this - 

```js
function terminus(server, { signal='SIGTERM', timeout=1000 } = {}) {
  //other stuff
}
```

If you like this, I can make a PR.

**Comment by vernak2539** [comment]
i believe it was done in order to support node version that don't support parameter destructuring and default params. I believe this changed on the transition from node 4 to 6. The more people able to use it with out a compile step the better I believe.

**Comment by itaditya** [comment]
> done in order to support node version that don't support parameter destructuring and default params

In this file https://github.com/godaddy/terminus/blob/master/lib/terminus.js#L20, object is already being destructured, so the node version supported will stay the same,

**Comment by vernak2539** [comment]
yes, but not with default values and not in the actual function parameters. i'm just pointing out why it may have been done

**Comment by gergelyke** [comment]
Based on node.green, default parameters should work with Node.js 6. I am ok with this change, as far as it passes the tests on Travis using Node@6

**Comment by itaditya** [comment]
Then I'll get on it ASAP
