### ISSUE TITLE
Missing background info and k8s configs for examples

### ISSUE THREAD

**Issue by peterkuiper** [godaddy/terminus#54]
I think a bit of background info about what actually happens on SIGTERM and maybe some example k8s yaml files to get people going would be great (readinessProbe, livenessProbe and terminationGracePeriodSeconds). Your [blog post](https://nemethgergely.com/nodejs-healthcheck-graceful-shutdown/) explains things a bit more in depth: things get [confusing](https://hackernoon.com/graceful-shutdown-in-kubernetes-435b98794461) :)

Maybe even an example of it working in action with minikube would be great. How can you confirm that everything is working correctly?

Either way, great module. I replaced our custom code (in the end did the same thing but with more clutter). We added a `const serverListenAsync = promisify(server.listen.bind(server))` so server startup steps can be nicely chained (ie, db connection, redis etc).

Does godaddy use terminus in production? Maybe there are some tips and tricks you can share.

**Comment by gergelyke** [comment]
Hi Peter,

yeah, that makes sense, I'll work on that!

Yes, we use it in production.

**Comment by peterkuiper** [comment]
If you need any help, please let me know!

**Comment by gergelyke** [comment]
Thanks @peterkuiper - once I have a PR ready, I will send it your way!

**Comment by gergelyke** [comment]
@peterkuiper managed to put together a first draft: https://github.com/godaddy/terminus/pull/58

please let me know what you'd change!

**Comment by gergelyke** [comment]
closing as https://github.com/godaddy/terminus/pull/58 is merged

**Comment by peterkuiper** [comment]
@gergelyke Sorry for the late response: LGTM!

**Comment by gergelyke** [comment]
cool, thanks @peterkuiper!
