### ISSUE TITLE
Signal handlers are not removed from process

### ISSUE THREAD

**Issue by wcho** [godaddy/terminus#60]
In the following code, cleanup is not the correct handler. 'sig => cleanup(sig)' is the correct one.
process.on(sig, sig => cleanup(sig))

**Comment by gergelyke** [comment]
hi @wcho - can you help me better understand the issue? are you referring to https://github.com/godaddy/terminus/blob/master/lib/terminus.js#L84?

can you help me how this whole snippet should look in your opinion?

```js
signals.forEach(
  sig => process.on(sig, sig => cleanup(sig))
)
```

**Comment by wcho** [comment]
I think `cleanup` should be registered as is so that it can be removed properly in https://github.com/godaddy/terminus/blob/master/lib/terminus.js#L80
```
signals.forEach(
  sig => process.on(sig, cleanup)
)
```

**Comment by gergelyke** [comment]
You are right @wcho - just created a PR: https://github.com/godaddy/terminus/pull/67

**Comment by gergelyke** [comment]
merged! :)
