### ISSUE TITLE
Return more info in the healthcheck endpoint

### ISSUE THREAD

**Issue by tnguyen14** [godaddy/terminus#64]
I was wondering if it'd be a good idea to allow the `healthcheck` promise-returning function to resolve back an object that could contain more info about the application that could be included in the `SUCCESS_RESPONSE`. 

Some of this info could include things like application version etc.

I understand that the info could be made available under a new endpoint, but I think it could make sense to include in the healthcheck one as well.

Please let me know what your thoughts are on this. If this seems reasonable, I'm more than happy to create a PR for it.

**Comment by gergelyke** [comment]
Sounds great @tnguyen14 ! Can you submit a PR that does this in a semver minor manner?

**Comment by gergelyke** [comment]
closing as https://github.com/godaddy/terminus/pull/65 is merged
