### ISSUE TITLE
use with nestjs

### ISSUE THREAD

**Issue by xmlking** [godaddy/terminus#70]
if it possible to use terminus  with https://nestjs.com/ ? 
i am interested in health checks

**Comment by gergelyke** [comment]
hi @xmlking !

i am not familiar with that framework, but if they expose the http server, you should be able to wrap that with terminus.

if you figure it out, can you send a PR that adds an example with nest?

**Comment by weeco** [comment]
@xmlking See https://github.com/nestjs/nest/issues/966

**Comment by gergelyke** [comment]
also, https://github.com/godaddy/terminus/issues/75

**Comment by BrunnerLivio** [comment]
Hello guys,

I am currently the maintainer of [nest/termins](). We're running in some issues which heavily involves the general codebase of `@godaddy/terminus`. 

The problems are described on [nest/termins#2](https://github.com/nestjs/terminus/issues/2#issuecomment-424699384)

The main problem is, we want to support subsystem of a health check e.g.

```JSON
{  
  "status":"DOWN",
  "reason":"fortniteClient is DOWN",
  "diskSpace":{  
    "status":"UP",
    "free":56443746,
    "threshold":1345660
  },
  "fortniteClient":{  
    "status":"DOWN",
    "error": {....}
  }
}
```

So for example when the status of a subsystem (e.g. `forniteClient` or `diskSpace`) equals down, the status of the health response should also be down. Also if a system is down, it should be able to print a detailed error message. These things are currently not possible with `@godaddy/terminus`. So if these kind of requirements are out of your scope, we would have to go with our own implementation..

**Comment by weeco** [comment]
Having the possibility to return objects would be nice because that certainly helps to understand why exactly the status is down (e. g. only 100mb diskspace left, but you need 200mb for your service to operate).

**Comment by gergelyke** [comment]
Sounds good - I can draft up a PR today to address this

**Comment by BrunnerLivio** [comment]
@gergelyke
Thanks a lot for your quick response & actions.

One problem I still see is, who verifies if the overall status is “up” or “down”? 

Easiest way is if the user can explicitly say whats the overall status. So he can decide if Subsystem A is up but Subsystem B is down, if that would crucial for the system or bot.

At the moment a User can only say if the overall status is up or down by throwing an error. Probably we need to find another solution for this, because the user also needs to send the status of the subsystems in addition as desribed before.

I think this could lead into breaking changes. Do you have an idea how you want to solve this?

**Comment by BrunnerLivio** [comment]
@gergelyke 
Yup.

**Comment by gergelyke** [comment]
how about something like this: https://github.com/godaddy/terminus/pull/81?

if you like the idea, I can expand on the docs / examples

**Comment by gergelyke** [comment]
@BrunnerLivio https://github.com/godaddy/terminus/releases/tag/v3.0.0 🎉

**Comment by BrunnerLivio** [comment]
@BrunnerLivio yup got it working, thanks a lot!

Only problem I currently have is the typings. Seems like they're not updated yet. I can do a PR for that. I think since this release #75 is doable.

**Comment by gergelyke** [comment]
released under https://github.com/godaddy/terminus/releases/tag/v3.0.1

thanks a lot for the contrib!
