### ISSUE TITLE
Export interfaces from typings

### ISSUE THREAD

**Issue by BrunnerLivio** [godaddy/terminus#75]
Hi everyone,

I am currently working on #70: [nest-terminus](https://github.com/brunnerlivio/nest-terminus). Good work with this repo, I like it!
I have a problem; I am exporting a terminus instance:

[terminus-lib.provider.ts](https://github.com/BrunnerLivio/nest-terminus/blob/master/lib/terminus-lib.provider.ts)

```TypeScript
import { TERMINUS_LIB } from './terminus.constants';
import * as terminus from '@godaddy/terminus';
import { TerminusOptions } from './interfaces/terminus-options';

export type TerminusLib = typeof terminus;

// Create a wrapper so it is injectable & easier to test
export const TerminusLibProvider = {
  provide: TERMINUS_LIB,
  useValue: terminus,
};

```

This small file is used so I can inject the terminus instance in Nest using the DI system. The problem is TSC is throw an error: 

```
Exported variable 'TerminusLibProvider' has or is using name 'TerminusOptions' from external module "@godaddy/terminus" but cannot be named.
```

The problem here is that `TerminusOptions` is being exported without importing it. It is a strange error, I know, but it could be fixed if the Typings get updated and the interface `TerminusOptions` gets exported too (tried it on my system and it worked)

Would you have a problem with exposing this interface?

**Comment by gergelyke** [comment]
Hi @BrunnerLivio! Sounds good - would you be up for sending a PR?

**Comment by BrunnerLivio** [comment]
> (tried it on my system and it worked)

Seems like I checked wrongly; it does not work, or at least I can not find any solution. 
The problem here is `@godaddy/terminus` does not have a default export. There for it can just export one instance. That is why TypeScript can't export any other types or at least I haven't found any solution after ~10-20 min googling. Not an expert in writing Typings for existing modules though, so maybe you find a solution.  

Breaking the API (change module.exports to module.exports['default']) would be too much to ask just for Typings, so I think I have to close this issue.

**Comment by gergelyke** [comment]
released under https://github.com/godaddy/terminus/releases/tag/v3.0.1
