### ISSUE TITLE
only usable with node versions >=7.6.0

### ISSUE THREAD

**Issue by vernak2539** [godaddy/terminus#8]
It seems as if the [stoppable][stoppable-module] module being used includes the [awaiting][awaiting-module] module, which only allows for use of node versions >=7.6.0.

This seems to be a big limitation, as v6 is an active LTS until April 2019. Unfortunately, we cannot update to 7+ yet, but would really like to use this module

Is it possible to use a different module or make the stoppable module not use awaiting? I see this all these modules seem to be made by the same people.

[awaiting-module]: https://www.npmjs.com/package/awaiting
[stoppable-module]: https://www.npmjs.com/package/stoppable

**Comment by jcrugzz** [comment]
@vernak2539 looks like @gergelyke properly moved that module to devDepdencies and we are just waiting on a new version to be published.

**Comment by gergelyke** [comment]
@jcrugzz @vernak2539 https://github.com/godaddy/terminus/pull/9

**Comment by gergelyke** [comment]
@vernak2539 released as https://github.com/godaddy/terminus/releases/tag/v2.0.1 🎉
