### ISSUE TITLE
Get the health status without using a HTTP request

### ISSUE THREAD

**Issue by BrunnerLivio** [godaddy/terminus#83]
## Issue

I would like to read out the current health status, without having to create a HTTP request.
Therefore the health status should be readable programmatically using the public Terminus API.

Something like this:

```JavaScript
const { getHealthStatus } = require('@godaddy/terminus');

// Returns { status: 'ok' | 'error', info: {...} }
getHealthStatus('/health');
```

## Implementation

Looking through your code, I realized the core (terminus.js) would have to get restructured if done correctly.

When I tried to refactor the method `decorateWithHealthCheck` in `terminus.js` which contains the desired functionality, I realized everything is handled over parameters. My refactored function would look like the following:

```JavaScript
function getHealthStatus(url, state, options) {
  const { healthChecks, logger } = options;
  if (state.isShuttingDown) {
    return sendFailure(res)
  }
  healthChecks[url]()
    .then((info) => {
      sendSuccess(res, info)
    })
    .catch((error) => {
      logger('healthcheck failed', error)
      sendFailure(res, error.causes)
    })
}
```

The problem is, a user should not pass `state` nor `options` as a parameter. Thus it is still required for the functionality of `getHealthStatus`. A way to solve this problem, is to use a class instance for each `createTerminus()` call, which then can handle `state` or `options` as a property.

**Comment by gergelyke** [comment]
Hi @BrunnerLivio - any chance you can work on a PR to address this? If not, I can take it on sometimes next week.

**Comment by BrunnerLivio** [comment]
I also do not know if I have time for this either, but try to look into it.

I think I have to break the public API (again :sweat_smile: ) in order to achieve this.

**Comment by gergelyke** [comment]
No worries - that's why we have semver :)

**Comment by gergelyke** [comment]
Closing this as per https://github.com/godaddy/terminus/pull/87
