### ISSUE TITLE
Possible semantic versioning issue

### ISSUE THREAD

**Issue by jacob-hd** [godaddy/terminus#88]
![image](https://user-images.githubusercontent.com/31864739/46559489-64236380-c8a5-11e8-8ffc-498a8bca87bc.png)

Am I reading this correctly? It looks like somehow `v4.1.0` and `v3.1.0` are pointing at the same codebase.. same with `v3.0.0` and `v2.6.0`

**Comment by gergelyke** [comment]
oh my - will look into this

**Comment by gergelyke** [comment]
going forward, it should work correctly - not sure what the glitch was
